version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: boards
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bar/lib/postgresql/data
  
