name: image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs: 
  create-docker-image:
    runs-on ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.QUEEN_TOKEN }}
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/bryan182/queens_puzzle:latest